name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gym-trainer-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/gym-trainer-backend:latest

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gym-trainer-frontend:latest --build-arg VITE_API_URL='${{ secrets.VITE_API_URL }}' ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/gym-trainer-frontend:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull backend image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/gym-trainer-backend:latest

      - name: Pull frontend image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/gym-trainer-frontend:latest

      - name: Delete old containers
        run: |
          docker rm -f backend-container || true
          docker rm -f frontend-container || true

      - name: Run backend container
        run: docker run -d -p 5000:5000 --name backend-container --log-opt max-size=10m --log-opt max-file=3 -e NODE_ENV='${{ secrets.NODE_ENV }}' -e MONGO_URI='${{ secrets.MONGO_URI }}' -e CORS_ORIGIN='${{ secrets.CORS_ORIGIN }}' -e SMTP_USER='${{ secrets.SMTP_USER }}' -e SMTP_PASS='${{ secrets.SMTP_PASS }}' -e ACCESS_TOKEN_SECRET='${{ secrets.ACCESS_TOKEN_SECRET }}' -e REFRESH_TOKEN_SECRET='${{ secrets.REFRESH_TOKEN_SECRET }}' -e FRONTEND_URL='${{ secrets.FRONTEND_URL }}' ${{ secrets.DOCKER_USERNAME }}/gym-trainer-backend:latest

      - name: Run frontend container
        run: docker run -d -p 3000:80 --name frontend-container --log-opt max-size=10m --log-opt max-file=3 ${{ secrets.DOCKER_USERNAME }}/gym-trainer-frontend:latest

      - name: Cleanup old Docker resources
        run: |
          docker image prune -a -f --filter "until=24h"
          rm -rf /home/ubuntu/node-runner/_work/_update || true
          rm -rf /home/ubuntu/node-runner/_diag/* || true
